---

- name: create pushgateway configuration directories
  file:
    path: "{{ pushgateway_config_directory }}"
    state: directory
    owner: root
    group: "{{ pushgateway_system_group }}"
    mode: 0770

- name: create systemd pushgateway config
  template:
    src: pushgateway.j2
    dest: "{{ pushgateway_config_directory }}/pushgateway"
    mode: 0644
  notify:
    - daemon-reload
    - restart pushgateway

- name: flush handlers
  meta: flush_handlers

...
