---

- block:
    - name: get checksum list
      set_fact:
        __pushgateway_checksums: "{{ lookup('url', 'https://github.com/prometheus/pushgateway/releases/download/v' + pushgateway_version + '/sha256sums.txt', wantlist=True) | list }}"
      run_once: true

    - name: get checksum for {{ go_arch }} architecture
      set_fact:
        __pushgateway_checksum: "{{ __pushgateway_checksums | pushgateway_checksum('linux', go_arch) }}"
  become: false
  delegate_to: localhost
  run_once: true

- name: download pushgateway binary archive
  become: false
  delegate_to: "{{ pushgateway_delegate_to }}"
  run_once: "{{ 'false' if pushgateway_direct_download else 'true' }}"
  get_url:
    url: "{{ pushgateway_release.download_url }}/download/v{{ pushgateway_version }}/{{ pushgateway_release.file }}"
    dest: "{{ pushgateway_local_tmp_directory }}/{{ pushgateway_release.file }}"
    checksum: "sha256:{{ __pushgateway_checksum }}"
  register: _download_archive
  until: _download_archive is succeeded
  retries: 5
  delay: 2
  check_mode: false

- name: extract pushgateway archive
  become: false
  delegate_to: "{{ pushgateway_delegate_to }}"
  run_once: "{{ 'false' if pushgateway_direct_download else 'true' }}"
  unarchive:
    src: "{{ pushgateway_local_tmp_directory }}/{{ pushgateway_release.file }}"
    dest: "{{ pushgateway_local_tmp_directory }}/"
    copy: false

...
