---

- name: download pushgateway binary archive
  become: false
  delegate_to: "{{ pushgateway_delegate_to }}"
  get_url:
    url: "{{ pushgateway_release.download_url }}/download/v{{ pushgateway_version }}/{{ pushgateway_release.file }}"
    dest: "{{ pushgateway_local_tmp_directory }}/{{ pushgateway_release.file }}"
  register: _download_archive
  until: _download_archive is succeeded
  retries: 5
  delay: 2
  check_mode: false

- name: extract pushgateway archive
  become: false
  delegate_to: "{{ pushgateway_delegate_to }}"
  unarchive:
    src: "{{ pushgateway_local_tmp_directory }}/{{ pushgateway_release.file }}"
    dest: "{{ pushgateway_local_tmp_directory }}/"
    copy: false

...
