---

- name: checksum
  become: false
  delegate_to: localhost
  run_once: true
  block:
    - name: get checksum list
      github_checksum:
        project: prometheus
        repository: pushgateway
        checksum_file: sha256sums.txt
        user: "{{ lookup('env', 'GH_USER') | default(omit) }}"
        password: "{{ lookup('env', 'GH_TOKEN') | default(omit) }}"
        architecture: "{{ ansible_architecture }}"
        system: "{{ ansible_facts.system }}"
        version: "{{ pushgateway_version }}"
      register: _latest_checksum

    - name: define checksum for {{ go_arch }} architecture
      ansible.builtin.set_fact:
        __pushgateway_checksum: "{{ _latest_checksum.checksum }}"
      when:
        - _latest_checksum.rc == 0
        - _latest_checksum.checksum is defined
        - _latest_checksum.checksum | string | length > 0

- name: download pushgateway binary archive
  become: false
  delegate_to: "{{ pushgateway_delegate_to }}"
  run_once: "{{ 'false' if pushgateway_direct_download else 'true' }}"
  ansible.builtin.get_url:
    url: "{{ pushgateway_release.download_url }}/download/v{{ pushgateway_version }}/{{ pushgateway_release.file }}"
    dest: "{{ pushgateway_local_tmp_directory }}/{{ pushgateway_release.file }}"
    checksum: "sha256:{{ __pushgateway_checksum }}"
    mode: 0660
  register: _download_archive
  until: _download_archive is succeeded
  retries: 5
  delay: 2
  check_mode: false

- name: extract pushgateway archive
  become: false
  delegate_to: "{{ pushgateway_delegate_to }}"
  run_once: "{{ 'false' if pushgateway_direct_download else 'true' }}"
  ansible.builtin.unarchive:
    src: "{{ pushgateway_local_tmp_directory }}/{{ pushgateway_release.file }}"
    dest: "{{ pushgateway_local_tmp_directory }}/"
    copy: false

...
