---

- name: detect binary file for pushgateway
  become: false
  delegate_to: "{{ pushgateway_delegate_to }}"
  run_once: "{{ 'false' if pushgateway_direct_download else 'true' }}"
  stat:
    path: "{{ pushgateway_local_tmp_directory }}/pushgateway-{{ pushgateway_version }}.linux-{{ go_arch }}/pushgateway"
  register: stat_file_binary

- name: fail when extracted binary are missing
  fail:
    msg: "missing extracted binary on ansible controller"
  when:
    - not stat_file_binary.stat.exists

- block:
    - name: propagate pushgateway binaries
      copy:
        src: "{{ pushgateway_local_tmp_directory }}/pushgateway-{{ pushgateway_version }}.linux-{{ go_arch }}/pushgateway"
        dest: "{{ pushgateway_install_path }}/pushgateway"
        mode: 0755
        owner: "{{ pushgateway_system_user }}"
        group: "{{ pushgateway_system_group }}"
        remote_src: "{{ 'true' if pushgateway_direct_download else 'false' }}"

    - name: make files executable
      file:
        path: "{{ pushgateway_install_path }}/pushgateway"
        mode: 0755
        owner: "{{ pushgateway_system_user }}"
        group: "{{ pushgateway_system_group }}"
  when:
    - stat_file_binary.stat.exists

- name: create link to binary
  file:
    src: "{{ pushgateway_install_path }}/pushgateway"
    dest: /usr/bin/pushgateway
    state: link
    force: true
  notify:
    - restart pushgateway

- name: create systemd service unit
  template:
    src: "init/systemd/pushgateway.service.j2"
    dest: "{{ systemd_lib_directory }}/pushgateway.service"
    owner: root
    group: root
    mode: 0644
  notify:
    - daemon-reload
    - restart pushgateway

...
