---

- name: detect binary file for pushgateway on {{ pushgateway_delegate_to }}
  become: false
  delegate_to: "{{ pushgateway_delegate_to }}"
  run_once: "{{ 'false' if pushgateway_direct_download else 'true' }}"
  ansible.builtin.stat:
    path: "{{ pushgateway_local_tmp_directory }}/pushgateway-{{ pushgateway_version }}.linux-{{ go_arch }}/pushgateway"
  register: stat_file_binary

- name: fail when extracted binary are missing
  ansible.builtin.fail:
    msg: "missing extracted binary on ansible controller"
  when:
    - not stat_file_binary.stat.exists

- name: propagate pushgateway binaries
  ansible.builtin.copy:
    src: "{{ pushgateway_local_tmp_directory }}/pushgateway-{{ pushgateway_version }}.linux-{{ go_arch }}/pushgateway"
    dest: "{{ pushgateway_install_path }}/pushgateway"
    mode: 0755
    owner: "{{ pushgateway_system_user }}"
    group: "{{ pushgateway_system_group }}"
    remote_src: "{{ 'true' if pushgateway_direct_download else 'false' }}"
  when:
    - stat_file_binary.stat.exists

- name: make files executable
  ansible.builtin.file:
    path: "{{ pushgateway_install_path }}/pushgateway"
    mode: 0755
    owner: "{{ pushgateway_system_user }}"
    group: "{{ pushgateway_system_group }}"

- name: create link to binary
  ansible.builtin.file:
    src: "{{ pushgateway_install_path }}/pushgateway"
    dest: /usr/bin/pushgateway
    state: link
    force: true
  notify:
    - restart pushgateway

- name: create local facts
  ansible.builtin.template:
    src: ansible_facts.j2
    dest: /etc/ansible/facts.d/pushgateway.fact
    mode: 0755

- name: create persistence directory
  ansible.builtin.file:
    state: directory
    owner: "{{ pushgateway_system_user }}"
    group: "{{ pushgateway_system_group }}"
    mode: 0750
    path: "{{ pushgateway_service.persistence.file | dirname }}"
  when:
    - pushgateway_service.persistence.file is defined
    - pushgateway_service.persistence.file | string | length > 0
      
- name: create systemd service unit
  ansible.builtin.template:
    src: "init/systemd/pushgateway.service.j2"
    dest: "{{ systemd_lib_directory }}/pushgateway.service"
    owner: root
    group: root
    mode: 0644
  notify:
    - daemon-reload
    - restart pushgateway
  when:
    - ansible_service_mgr | lower == "systemd"

...
