---

- name: prepare
  include_tasks: prepare.yml

- name: download archive
  include_tasks: download.yml
  when:
    - not stat_pushgateway_binary.stat.exists or
      not stat_pushgateway_binary.stat.path == pushgateway_install_path ~ '/pushgateway'

- name: install
  include_tasks: install.yml
  when:
    - not stat_pushgateway_binary.stat.exists or
      not stat_pushgateway_binary.stat.path == pushgateway_install_path ~ '/pushgateway'

- name: configure
  include_tasks: configure.yml

- name: service
  include_tasks: service.yml

...
