---

- name: restart pushgateway if needed
  ansible.builtin.meta: flush_handlers

- name: ensure pushgateway is enabled on boot
  become: true
  ansible.builtin.service:
    name: pushgateway
    enabled: true
    state: started

...
