---

- name: restart pushgateway
  become: true
  ansible.builtin.service:
    name: pushgateway
    state: restarted

- name: reload pushgateway
  become: true
  ansible.builtin.service:
    name: pushgateway
    state: reloaded

- name: daemon-reload
  become: true
  ansible.builtin.systemd:
    daemon_reload: true
    force: true
  when:
    - ansible_service_mgr | lower == "systemd"

...
